/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package zanagram

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun `add makes list not empty`() {
        var list: Node<Int>? = null

        list = add(1, list)

        assertNotNull(list, "list should not be empty")
        assertEquals(1, list.data)
    }

    @Test
    fun `size of empty list is zero`() {
        var list: Node<Int>? = null

        assertEquals(0, size(list))
    }

    @Test
    fun `add 1 should make size equal 1`() {
        var list: Node<Int>? = null

        list = add(1, list)

        assertEquals(1, size(list))
    }
}
